# Generated by Django 2.2.13 on 2021-01-25 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='postview',
            name='view_count',
            field=models.IntegerField(default=0),
        ),
    ]
