# Generated by Django 2.2.13 on 2021-01-26 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectsview',
            name='view_count',
            field=models.IntegerField(default=0),
        ),
    ]
