# Generated by Django 2.2.13 on 2021-01-08 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0002_auto_20210108_0939'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gallery',
            old_name='content',
            new_name='gallery_content',
        ),
    ]
