# Generated by Django 2.2.13 on 2021-01-08 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0003_auto_20210108_1144'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gallery',
            old_name='gallery_content',
            new_name='content',
        ),
    ]
