# Generated by Django 2.2.13 on 2021-01-26 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0004_auto_20210108_1556'),
    ]

    operations = [
        migrations.AddField(
            model_name='galleryview',
            name='view_count',
            field=models.IntegerField(default=0),
        ),
    ]
