# Generated by Django 2.2.13 on 2021-02-08 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0006_auto_20210126_1132'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gallery',
            name='author',
        ),
    ]
