# Generated by Django 2.2.13 on 2021-02-08 13:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0007_remove_gallery_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallery',
            name='author',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='gallery.GalleryAuthor'),
            preserve_default=False,
        ),
    ]
