# Generated by Django 2.2.13 on 2021-02-08 14:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0008_gallery_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallery',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posts.Author'),
        ),
    ]
