# Generated by Django 2.2.13 on 2021-02-08 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0009_auto_20210208_1514'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GalleryAuthor',
        ),
    ]
